# docker compose -f docker-compose-dev.yml up

version: "3.1"

# secrets:
#     my_secret:
#      file: ./my_secret.txt

services:
  app:
    build: .
    container_name: nightscout-alphatrak-uploader
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - c:\Users\nicol\OneDrive\Documents\GitHub\ENV\nightscout-alphatrak-uploader.env
    command: python -u package/main.py --reload
    volumes:
      - .:/app
    # secrets:
    #   - my_secret
   